### ISSUE TITLE
Hi! I have a problem...  Billing

### ISSUE THREAD

**Issue by brandonvers** [mrv-gamepanel/mrv.gp.open#1]
Warning: PDOStatement::execute(): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'id' cannot be null in /var/www/html/core/class/db.class.php on line 64
["error","Sorry there was an error, please try again later!"]

( http://37.221.211.78/process?orderServer )

**Comment by DEAM0** [comment]
disable strict-mode mysql
